name: CI-Build

on:
  push:
    branches: [ develop, master, release/*, hotfix/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      src-directory: ./src

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403

    - name: Cache Tools
      uses: actions/cache@v2
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
  
    - name: Build project
      uses: cake-build/cake-action@v1
      with:
        script-path: recipe.cake
        target: CI
        verbosity: Verbose
        cake-version: 0.38.4
        cake-bootstrap: true

    - name: Upload Issues-Report artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        if-no-files-found: warn
        name: issues
        path: BuildArtifacts/report.html

    - name: Upload nuget packages artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        if-no-files-found: warn
        name: package
        path: BuildArtifacts/Packages/**/*
