name: CI-Build

on:
  push:
    branches: [ develop, master, release/*, hotfix/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      src-directory: ./src

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403

    - name: Cache Tools
      uses: actions/cache@v2
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
  
    - name: Build project
      uses: cake-build/cake-action@v1
      with:
        script-path: recipe.cake
        target: CI
        verbosity: Normal
        cake-version: 0.38.4
        cake-bootstrap: true

    - name: Publish Issues-Report
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: issues
        path: BuildArtifacts/report.html

    - name: Publish nuget packages
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: package
        path: BuildArtifacts/Packages/**/*

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./BuildArtifacts/TestCoverage/coverlet/oehen-arguard.opencover.xml   
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov
        fail_ci_if_error: true
        path_to_write_report: ./BuildArtifacts/TestCoverage/coverlet/codecov_report.gz
        verbose: true

    - name: Publish codecov report
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: codecov
        path: ./BuildArtifacts/TestCoverage/coverlet/*
