name: CI-Build

on:
  push:
    paths-ignore:
      - "README.md"
    branches: [develop, master]
    tags: 
      - '*'
    
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-13 ]

    env:
      src-directory: ./src

      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # GPR - PRERELEASE
      GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
      GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      # NUGET - RELEASE
      NUGET_SOURCE: https://nuget.org/api/v2/package
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      # WYAM - DOCUMENTATION
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}
      WYAM_DEPLOY_BRANCH: gh-pages
      # CODCOV
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
    steps:
    - name: Checkout the repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    # node setup
    - name: Setup node 20
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version: 20

    # .net Core setup
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: 3.1

    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: 5.x

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: 6.x

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: 8.x

    # Caching Tools
    - name: Cache Tools
      uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
  
    # Build
    - name: Build Project
      uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
      with:
        script-path: recipe.cake
        target: CI
        verbosity: Verbose
        cake-version: 1.3.0
        cake-bootstrap: true

    # Publish artifacts
    - name: Publish Issues-Report as build artifact
      uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
      if: matrix.os == 'windows-latest'
      with:
        if-no-files-found: warn
        name: Issue Report
        path: BuildArtifacts/report.html

    - name: Publish NuGet package as build artifact
      uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
      if: matrix.os == 'ubuntu-22.04'
      with:
        if-no-files-found: warn
        name: NuGet Package
        path: BuildArtifacts/Packages/**/*

    - name: Publish coverage artifact
      uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
      if: matrix.os == 'ubuntu-22.04'
      with:
        if-no-files-found: warn
        name: Coverage
        path: BuildArtifacts/TestCoverage/coverlet/*.xml
