name: CI-Build

on:
  push:
    paths-ignore:
      - "README.md"
    branches: [develop, master]
    
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-latest, macos-latest ]

    env:
      src-directory: ./src
      # workaround for https://github.com/cake-contrib/Cake.Recipe/issues/724
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # GPR - PRERELEASE
      GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
      GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      # NUGET - RELEASE
      NUGET_SOURCE: https://nuget.org/api/v2/package
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      # WYAM - DOCUMENTATION
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}
      WYAM_DEPLOY_BRANCH: gh-pages
      
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    # .net Core setup
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    # Caching Tools
    - name: Cache Tools
      uses: actions/cache@v2.1.5
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
  
    # Build
    - name: Build Project
      uses: cake-build/cake-action@v1
      with:
        script-path: recipe.cake
        target: CI
        verbosity: Verbose
        cake-version: 0.38.5
        cake-bootstrap: true
    
    # Publish artifacts
    - name: Publish Issues-Report as build artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        if-no-files-found: warn
        name: Issue Report
        path: BuildArtifacts/report.html

    - name: Publish NuGet package as build artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-18.04'
      with:
        if-no-files-found: warn
        name: NuGet Package
        path: BuildArtifacts/Packages/**/*

    - name: Publish coverage artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-18.04'
      with:
        if-no-files-found: warn
        name: Coverage
        path: BuildArtifacts/TestCoverage/coverlet/*.xml

    # Publish external
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      if: matrix.os == 'ubuntu-18.04'
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: BuildArtifacts/TestCoverage/coverlet/*.xml

