name: PR-Build

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      src-directory: ./src
      # workaround for https://github.com/cake-contrib/Cake.Recipe/issues/724
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    # .net Core setup
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    # Caching Tools
    - name: Cache Tools
      uses: actions/cache@v2.1.4
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
  
    # Build
    - name: Build Project
      uses: cake-build/cake-action@v1
      with:
        script-path: recipe.cake
        target: CI
        verbosity: Verbose
        cake-version: 0.38.5
        cake-bootstrap: true
    
    # Publish
    - name: Publish Issues-Report as build artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        if-no-files-found: warn
        name: Issue Report
        path: BuildArtifacts/report.html

    - name: Publish NuGet package as build artifact
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        if-no-files-found: warn
        name: NuGet Package
        path: BuildArtifacts/Packages/**/*
