name: PR-Build

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-13 ]

    env:
      src-directory: ./src

      # CODCOV
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    # .net Core setup
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 3.1

    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 5.x

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 6.x

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 8.x

    - name: Use Node.js 20
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: 20

    # Caching Tools
    - name: Cache Tools
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
  
    # Build
    - name: Build Project
      uses: cake-build/cake-action@v2
      with:
        script-path: recipe.cake
        target: CI
        verbosity: Verbose
        cake-version: 1.3.0
        cake-bootstrap: true
    
    # Publish
    - name: Publish Issues-Report as build artifact
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
      if: matrix.os == 'windows-latest'
      with:
        if-no-files-found: warn
        name: Issue Report
        path: BuildArtifacts/report.html

    - name: Publish NuGet package as build artifact
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
      if: matrix.os == 'ubuntu-22.04'
      with:
        if-no-files-found: warn
        name: NuGet Package
        path: BuildArtifacts/Packages/**/*

    - name: Publish coverage artifact
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
      if: matrix.os == 'ubuntu-22.04'
      with:
        if-no-files-found: warn
        name: Coverage
        path: BuildArtifacts/TestCoverage/coverlet/*.xml
